import AppShell from "@/components/AppShell";
import { createServerSupabaseClient } from "@/lib/supabase-server";

export default async function Reports(){
 const s=await createServerSupabaseClient(); const [{data:loans},{data:payments},{count:borrowers}]=await Promise.all([s.from("loans").select("original_amount,balance,status,product"),s.from("payments").select("amount,payment_date"),s.from("borrowers").select("*",{count:"exact",head:true})]);
 const original=(loans??[]).reduce((a:any,x:any)=>a+Number(x.original_amount),0); const outstanding=(loans??[]).reduce((a:any,x:any)=>a+Number(x.balance),0); const collected=(payments??[]).reduce((a:any,x:any)=>a+Number(x.amount),0); const overdue=(loans??[]).filter((x:any)=>x.status==="overdue").length; const rate=original?Math.round(((original-outstanding)/original)*100):0;
 return <AppShell><div className="heading"><div><h1>Reports & Monitoring</h1><div className="sub">Real-time portfolio metrics from the database.</div></div></div><div className="kpis"><K label="Total Collected" value={`₱${collected.toLocaleString()}`}/><K label="Outstanding" value={`₱${outstanding.toLocaleString()}`}/><K label="Overdue Accounts" value={overdue}/><K label="Collection Rate" value={`${rate}%`}/></div><div className="grid2"><div className="card"><h3>Portfolio Summary</h3><table style={{marginTop:15}}><tbody><tr><td>Borrowers</td><td><b>{borrowers??0}</b></td></tr><tr><td>Loan accounts</td><td><b>{loans?.length??0}</b></td></tr><tr><td>Original portfolio</td><td><b>₱{original.toLocaleString()}</b></td></tr><tr><td>Outstanding</td><td><b>₱{outstanding.toLocaleString()}</b></td></tr></tbody></table></div><div className="card"><h3>Loan Products</h3>{Object.entries((loans??[]).reduce((a:any,l:any)=>(a[l.product]=(a[l.product]||0)+1,a),{})).map(([p,n]:any)=><div key={p} style={{marginTop:15}}><div style={{display:"flex",justifyContent:"space-between"}}><span>{p}</span><b>{n}</b></div><div className="progress" style={{marginTop:6}}><i style={{width:`${Math.min(100,Number(n)/(loans?.length||1)*100)}%`}}/></div></div>)}</div></div></AppShell>
}
function K({label,value}:{label:string,value:any}){return <div className="kpi"><div className="kpi-top"><span>{label}</span><span className="kpi-icon">₱</span></div><strong>{value}</strong></div>}
